### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by andyplak** [andyplak/events-manager-pro-world-pay#1]
Version 1.0
- [x] Clone current PayPal gateway and rename classes / funtions
- [x] Admin Gateway settings
- [x] Booking form submision redirects to WorldPay
- [x] Handle Payment Response
- [x] Add optional Payment Response password
- [x] Add optional MD5 signature
- [x] Allow customer to chose card type on WordPress site
- [ ] Add validFrom -> validTo auth params based on EM booking timeout settings
- [ ] Resume payment (em_my_bookings_booking_actions)
- [x] Disable plugin if Events Manager Pro is not enabled
